services:
  stremio:
    build:
      context: .
      dockerfile: Dockerfile.nvidia
    image: local/stremio-simple:latest
    restart: unless-stopped
    environment:
      - NO_CORS=1
      - AUTO_SERVER_URL=0
      - IPADDRESS=192.168.0.100
      - SERVER_URL=https://192.168.0.100:8085
      - WEBUI_INTERNAL_PORT=8080
    ports:
      - "8085:8080"
    volumes:
      - "/mnt/lvm1-storage/.stremio-server:/root/.stremio-server"
    # Usar o NVIDIA Container Runtime
    runtime: nvidia
