services:
  stremio:
    image: tsaridas/stremio-docker:latest
    restart: unless-stopped
    environment:
      NO_CORS: 1
      AUTO_SERVER_URL: 1
      #IPADDRESS: 192.168.1.10 # Setup your ip address here
    ports:
      - "8080:8080"
    volumes:
      - "/srv/config/stremio/:/root/.stremio-server" # set the first part to your local folder. Its not required though
